const data_paquetes= [
    {
        id: 1,
        index: true,
        image: '/images/Buenos_aires.webp',
        alt_image: 'Buenos_Aires',
        description:'Buenos Aires en 5 días',
        price: '$25.000',
        discount: '40%',
    },
    {
        id: 2,
        index: true,
        image: '/images/Mendoza.webp',
        alt_image: 'Mendoza',
        description:'Mendoza en 4 días',
        price: '$18.000',
        discount: '20%',
    },
    {
        id: 3,
        index: true,
        image: '/images/Bariloche300x200.webp',
        alt_image: 'Bariloche',
        description:'Buenos Aires en 7 días',
        price: '$80.000',
        discount: '15%',
    },
    {
        id: 4,
        index: true,
        image: '/images/Calafate300x200.webp',
        alt_image: 'Calafate',
        description:'Calafate en 3 días',
        price: '$50.000',
        discount: '10%',
    },
    {
        id: 5,
        index: false,
        image: '/images/FinDelMundo300x200.webp',
        alt_image: 'Fin del Mundo',
        description:'Fin del Mundo en 6 días',
        price: '$75.000',
        discount: '45%',
    },
    {
        id: 6,
        index: false,
        image: '/images/Iguazu300x200.webp',
        alt_image: 'Iguazu',
        description:'Iguazus en 3 días',
        price: '$28.000',
        discount: '50%',
    },
    {
        id: 7,
        index: false,
        image: '/images/Ushuaia300x200.webp',
        alt_image: 'Ushuaia',
        description:'Ushuaia Aires en 7 días',
        price: '$85.000',
        discount: '40%',
    },
    {
        id: 8,
        index: false,
        image: '/images/SanRafael300x200.webp',
        alt_image: 'San Rafel',
        description:'San Rafel en 5 días',
        price: '$45.000',
        discount: '40%',
    },
    
];

module.exports= data_paquetes;